---
- name: Tarea de configuracion del examen
  hosts: localhost
  become: yes
  tasks:
    - name: Crear estructura de directorios en /tmp
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /tmp/2do_parcial/
        - /tmp/2do_parcial/alumno
        - /tmp/2do_parcial/equipo

    - name: Renderizar datos del alumno
      template:
        src: datos_alumno.txt.j2
        dest: /tmp/2do_parcial/alumno/datos_alumno.txt

    - name: Renderizar datos del equipo
      template:
        src: datos_equipo.txt.j2
        dest: /tmp/2do_parcial/equipo/datos_equipo.txt

    - name: Configurar sudoers para el grupo 2PSupervisores
      copy:
        content: "%2PSupervisores ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/2psupervisores
        validate: /usr/sbin/visudo -cf %s
